# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "polaris-app"
client_id = "ae5a05879e8d77a8776bc1e281648a71"
application_url = "https://solomon-eating-modem-work.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://solomon-eating-modem-work.trycloudflare.com/auth/callback",
  "https://solomon-eating-modem-work.trycloudflare.com/auth/shopify/callback",
  "https://solomon-eating-modem-work.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "e-com-faq.myshopify.com"
